In [1]:
import numpy as np
import tensorflow as tf
import random
import matplotlib.pyplot as plt

# rank 0: scalar
# rank 1: vector
# rank 2: matrix
# rank 3+: tensor

In [3]:
SEED_VALUE = 42

# Fix random number seed
random.seed(SEED_VALUE)
np.random.seed(SEED_VALUE)
tf.random.set_seed(SEED_VALUE)
tf.random.set_seed(SEED_VALUE)

In [4]:
# Tensorflow constant
rank_0_tensor = tf.constant(3)
print(rank_0_tensor)

rank_0_tensor = tf.constant(3.14)
print(rank_0_tensor)

rank_0_tensor = tf.constant(3.14, dtype=tf.float64)
print(rank_0_tensor)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(3.14, shape=(), dtype=float32)
tf.Tensor(3.14, shape=(), dtype=float64)


In [5]:
# Create rank 1 constant
rank_1_tensor = tf.constant([2.0, 4.0, 6.0])
print(rank_1_tensor)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)


In [7]:
rank_2 = tf.constant([[1,2],
                      [3,4],
                      [5,6]], dtype=tf.int32)
print(rank_2)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [8]:
# Create two constant tensors.
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [10, 11, 12]])

print(t1)
print('\n')
print(t2)
print('\n')

# Concatenate tensors along axis-0, along row
print(tf.concat([t1, t2], axis=0))
print('\n')

# Concatenate tensors along axis-1, along column
print(tf.concat([t1, t2], axis=1))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [10]:
# Create a tensor variable.
tensor = tf.Variable([2, 4])

# Attempt to assign a new value to 0-th tensor element
# = cannot be used, assign should be used
try:
    tensor[0] = 11
    print('Tensor: ', tensor)
except TypeError:
    print("\nError: A tensor object does not support item assignment")


Error: A tensor object does not support item assignment


In [11]:
# You must use the assign() method to assign a new value to a tensorflow variable
tensor[0].assign(42)
print(tensor[0])
print(tensor[1])

tf.Tensor(42, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [12]:
# Reduce function
# Create some data.
x = 10 * tf.random.uniform(shape=[3,5])
print(x)

# Compute the following quantities for all axes..
xmin  = tf.reduce_min (x)
xmax  = tf.reduce_max (x)
xmean = tf.reduce_mean(x)
xsum  = tf.reduce_sum (x)

print('\nComputed over all axes:\n')
print('min:  ', xmin)
print('max:  ', xmax)
print('mean: ', xmean)
print('sum:  ', xsum)

tf.Tensor(
[[6.6456213  4.4100676  3.528825   4.6448255  0.33660412]
 [6.8467236  7.4011745  8.724445   2.2632635  2.2319686 ]
 [3.103881   7.223358   1.3318717  5.4806385  5.746088  ]], shape=(3, 5), dtype=float32)

Computed over all axes:

min:   tf.Tensor(0.33660412, shape=(), dtype=float32)
max:   tf.Tensor(8.724445, shape=(), dtype=float32)
mean:  tf.Tensor(4.6612906, shape=(), dtype=float32)
sum:   tf.Tensor(69.91936, shape=(), dtype=float32)


In [13]:
# Compute the quantities for axis = 1.
xmin  = tf.reduce_min (x, axis=1)
xmax  = tf.reduce_max (x, axis=1)
xmean = tf.reduce_mean(x, axis=1)
xsum  = tf.reduce_sum (x, axis=1)

print('\nComputed for axis 1:\n')
print('min:  ', xmin)
print('max:  ', xmax)
print('mean: ', xmean)
print('sum:  ', xsum)


Computed for axis 1:

min:   tf.Tensor([0.33660412 2.2319686  1.3318717 ], shape=(3,), dtype=float32)
max:   tf.Tensor([6.6456213 8.724445  7.223358 ], shape=(3,), dtype=float32)
mean:  tf.Tensor([3.913189  5.493515  4.5771675], shape=(3,), dtype=float32)
sum:   tf.Tensor([19.565945 27.467575 22.885838], shape=(3,), dtype=float32)


In [15]:
# Indexing: gather --- now using numpy
# Create some data.
num_data = 24
data = np.random.uniform(0, 10, num_data)
print('data: \n', data)
print('\n')

# Create an array of random indices.
indices = np.random.choice(data.shape[0], 5, replace=False)
print('indices: ', indices)
print('\n')

# Use the indices array to select the corresponding elements from the data array.
selected_data = data[indices]

print('selected_data: ', selected_data)


data: 
 [1.22038235 4.9517691  0.34388521 9.09320402 2.58779982 6.62522284
 3.11711076 5.20068021 5.46710279 1.84854456 9.69584628 7.75132823
 9.39498942 8.9482735  5.97899979 9.21874235 0.88492502 1.95982862
 0.45227289 3.25330331 3.8867729  2.71349032 8.28737509 3.56753327]


indices:  [18  3  5  1  4]


selected_data:  [0.45227289 9.09320402 6.62522284 4.9517691  2.58779982]


In [16]:
# gathering using tensorflow
num_data = 24
data = tf.random.uniform(shape=[num_data])
print('data: \n', data)
print('\n')

# Create an array of random indices.
indices = tf.random.uniform([5], minval=0, maxval=len(data)-1, dtype=tf.dtypes.int32)
print('indices: ', indices)
print('\n')

# Use this he gather() method to index one tensor by another tensor.
selected_data = tf.gather(data, indices)

print('selected_data: ', selected_data)

data: 
 tf.Tensor(
[0.68789124 0.48447883 0.9309944  0.252187   0.73115396 0.89256823
 0.94674826 0.7493341  0.34925628 0.54718256 0.26160395 0.69734323
 0.11962581 0.53484344 0.7148968  0.87501776 0.33967495 0.17377627
 0.4418521  0.9008261  0.13803864 0.12217975 0.5754491  0.9417181 ], shape=(24,), dtype=float32)


indices:  tf.Tensor([ 6  3  2 15  1], shape=(5,), dtype=int32)


selected_data:  tf.Tensor([0.94674826 0.252187   0.9309944  0.87501776 0.48447883], shape=(5,), dtype=float32)


In [17]:
# Create a random tensor.
tensor = tf.random.normal(shape=[5, 3])
print(tensor)
print('\n')

# Create a tensor with indices.
rows = tf.constant([0, 2, 4])
cols = tf.constant([0, 2])

print('1st, 3rd, and 5th rows:')

# Access specific rows of a tensor by specifying the
# indices of the rows along with the row axis.
print(tf.gather(tensor, rows, axis=0))

print('\n')
print('1st and 3rd, cols:')

# Access specific cols of a tensor by specifying the
# indices of the cols along with the col axis.
print(tf.gather(tensor, cols, axis=1))

tf.Tensor(
[[ 0.65648675 -0.4130517   0.33997506]
 [-1.0056272   0.70266235 -1.4008642 ]
 [-0.89780754 -0.34856176 -0.95890623]
 [ 1.1948482   0.8507053  -0.30878615]
 [ 0.31389382  0.41766927  1.0629053 ]], shape=(5, 3), dtype=float32)


1st, 3rd, and 5th rows:
tf.Tensor(
[[ 0.65648675 -0.4130517   0.33997506]
 [-0.89780754 -0.34856176 -0.95890623]
 [ 0.31389382  0.41766927  1.0629053 ]], shape=(3, 3), dtype=float32)


1st and 3rd, cols:
tf.Tensor(
[[ 0.65648675  0.33997506]
 [-1.0056272  -1.4008642 ]
 [-0.89780754 -0.95890623]
 [ 1.1948482  -0.30878615]
 [ 0.31389382  1.0629053 ]], shape=(5, 2), dtype=float32)


In [18]:
# Interoperatibility: tensor to numpy and back
# Create a python list.
python_list = [1, 2]

# Create a NumPy array from the list.
numpy_array = np.array(python_list)

# Create a tensor from list.
tensor_from_list = tf.convert_to_tensor(python_list)

# Create a tensor from a NumPy array.
tensor_from_array = tf.convert_to_tensor(numpy_array)

# Create a NumPy array from a tensor.
array_from_tensor = tensor_from_array.numpy()

print('List:   ', python_list)
print('Array:  ', numpy_array)
print('Tensor: ', tensor_from_list)
print('Tensor: ', tensor_from_array)
print('Array:  ', array_from_tensor)

List:    [1, 2]
Array:   [1 2]
Tensor:  tf.Tensor([1 2], shape=(2,), dtype=int32)
Tensor:  tf.Tensor([1 2], shape=(2,), dtype=int64)
Array:   [1 2]
